version: '3.9'
services:
  app:
    build: ./infra/php
    ports:
      - 5173:5173
    volumes:
      - ./src:/data

  web:
    build: ./infra/nginx
    ports:
      - 8081:443
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - maildir:/tmp

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - 9000:9001
      - 9001:9002
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    entrypoint: sh
    command: -c "/opt/bin/minio server /export --address :9001 --console-address :9002"
    volumes:
      - ./infra/minio:/export

volumes:
  db-store:
  maildir:
