version: '3.9'
services:
  app:
    build: ./infra/php
    ports:
      - 5173:5173
    volumes:
      - ./src:/data

  web:
    build: ./infra/nginx
    ports:
      - 8081:443
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - maildir:/tmp

volumes:
  db-store:
  maildir:
